//! Handler name resolution for completion handlers.
//!
//! This module is `#[doc(hidden)]` — it is an implementation detail used by
//! macro-generated code to resolve completion handler function names to their
//! Restate handler names.
//!
//! Note: Resolution uses `std::any::type_name` to extract the method name from
//! the function item type. The format of `type_name` is not guaranteed by the
//! Rust spec, but in practice is stable for function items across all rustc versions.

use super::request::CompletionHandlerFnT;

/// Resolves a completion handler function to its Restate handler name.
///
/// Generic over `S` (the service impl type) so that each service's resolver
/// is scoped to its own handler set. Implemented by macro-generated resolver
/// structs (one per object/workflow service).
///
/// Resolution is infallible — the `CompletionHandlerFnT<S, Res>` bound on `F`
/// guarantees `F` is a valid handler on `S`, and the resolver is generated from
/// the same trait definition. If the match fails, it is a bug in code generation.
pub trait NameResolution<S> {
    fn resolve<Res, F: CompletionHandlerFnT<S, Res>>() -> &'static str;
}

/// Links a service impl type to its handler name resolver.
///
/// Implemented by the `#[restate_sdk::completion]` macro on the user's
/// concrete struct, connecting it to the resolver generated by the trait macro.
pub trait NamedService: Sized {
    type Resolution: NameResolution<Self>;
}
